### ISSUE TITLE
SPARQL  endpoint

### ISSUE THREAD

**Issue by glaserL** [dbpedia/gfs#11]
Hey, thank you very much for your work! 

I am currently trying to link dbpedia entries to wikidata. Luckily, dbpedia has a owl:sameAs relation to `https://global.dbpedia.org/id`, at least for the stuff I am trying to get. When I search your service in the web, i can see it contains the Q-entry that I am looking for. Is there any way to query your data base using SPARQL? 
Hope you can help me, best regards Luis

**Comment by JJ-Author** [comment]
Hi, can you elaborate what you want to do, please? No at the moment there is no SPARQL endpoint. But Linked Data (which could be fetched on demand within your own SPARQL endpoint, like with Virtuoso) 

`curl -H "Accept: text/turtle" https://global.dbpedia.org/id/12Qpnc`

for Virtuoso see e.g. https://medium.com/virtuoso-blog/what-is-the-virtuoso-sponger-middleware-about-and-why-is-it-important-293546b32a32  

We also have some code to create an RDF view of the clustering for the GFS data. We could create a file which would look like this that you can load to your own SPARQL endpoint. Would that help? 

``` <https://global.dbpedia.org/id/1zzzx> <http://dbpedia.org/cartridge/vocab/linked> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<https://global.dbpedia.org/id/1zzzx> <http://www.w3.org/2002/07/owl#sameAs> <https://global.dbpedia.org/id/1zzzx> .
<https://global.dbpedia.org/id/21118> <http://dbpedia.org/cartridge/vocab/fromSource> <http://d-nb.info/> .
<https://global.dbpedia.org/id/21118> <http://dbpedia.org/cartridge/vocab/fromSource> <http://data.bibliotheken.nl/> .
<https://global.dbpedia.org/id/21118> <http://dbpedia.org/cartridge/vocab/fromSource> <http://de.dbpedia.org/> .
<https://global.dbpedia.org/id/21118> <http://dbpedia.org/cartridge/vocab/fromSource> <http://viaf.org/> .
<https://global.dbpedia.org/id/21118> <http://dbpedia.org/cartridge/vocab/fromSource> <http://www.wikidata.org/> .
<https://global.dbpedia.org/id/21118> <http://dbpedia.org/cartridge/vocab/linked> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<https://global.dbpedia.org/id/21118> <http://www.w3.org/2002/07/owl#sameAs> <http://d-nb.info/gnd/1090396120> .
<https://global.dbpedia.org/id/21118> <http://www.w3.org/2002/07/owl#sameAs> <http://d-nb.info/gnd/128963263> .
<https://global.dbpedia.org/id/21118> <http://www.w3.org/2002/07/owl#sameAs> <http://data.bibliotheken.nl/id/thes/p283577053> .
<https://global.dbpedia.org/id/21118> <http://www.w3.org/2002/07/owl#sameAs> <http://de.dbpedia.org/resource/Walter_Feichtinger> .
<https://global.dbpedia.org/id/21118> <http://www.w3.org/2002/07/owl#sameAs> <http://viaf.org/viaf/52755195> .
<https://global.dbpedia.org/id/21118> <http://www.w3.org/2002/07/owl#sameAs> <http://www.wikidata.org/entity/Q21061473> .
<.

```

But this would take 1-2 weeks until we can deliver this.

**Comment by glaserL** [comment]
Hey, thanks a lot for the reply! Yes that would be what I need, but I found an alternative after fiddling around a bit: I now query "https://global.dbpedia.org/?s=URI", this gives me all the links but I then just filter for the wikidata stuff. I only need to do this once for the dbpedia urls I have, so I guess I won't spam you much, hope that is ok.

Thanks a lot for your help!
